spring:
  datasource:
      url: jdbc:mysql://localhost:3306/demo?useSSL=true
      username: root
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQL5Dialect
  output:
    ansi:
      enabled: ALWAYS

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ROOT: INFO
    com.test: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
