server:
  port: 11968

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/demo?useSSL=true
      username: root
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
management:
  endpoints:
    web:
      exposure:
        include: "*"